### ISSUE TITLE
リンクをクリックしてスクロールする速度がやや遅い (気がする)

### ISSUE THREAD

**Issue by akif999** [Taka-hyt/aletta#7]
個人的な感覚にはなりますが、当該処理の速度がやや遅いように感じます。

UI/UX 的に、近日の端末の GUI の操作感から考えると、500ms くらいがよいのでは??と思います。

これは実際にいろんな人に聞いてみるのが良さそう。
いずれにせよ、UI/UX の向上のために最適な値を検討する。

**Comment by akif999** [comment]
いまは「目的までに到達する時間」が統一されている。
もしかしたら「目的までスクロールする速度」を統一した方がよいかもしれない。
(やるとめんどくさい感はあるが)

**Comment by Taka-hyt** [comment]
スクロールする時間については「500ms」で統一しました。

**Comment by akif999** [comment]
8ca6d0a5 にて対応済み。
最終的な値は 600ms となった。

良いと思います。

**Comment by akif999** [comment]
close.
