### ISSUE TITLE
Concept Stylist の画像の解像度が辛い

### ISSUE THREAD

**Issue by akif999** [Taka-hyt/aletta#8]
これは既知の問題とのこと。

2019/9/T に画像を差し替えて対応される予定。

**Comment by Taka-hyt** [comment]
画像については全て差替えます。
9/3(火)に撮影予定となっています。(雨天時は変更の可能性有)
予定通り撮影できれば、9/3中に差し替えます。

**Comment by akif999** [comment]
095d48b79a1508277b928008a938579c68f8abbe 時点で対応済み。

**Comment by akif999** [comment]
close.
